FROM node:18-alpine

WORKDIR /usr/src/app

ENV DB_HOST mongodb://mongodb:27017
ENV DB_NAME db-contacts
ENV DB_USER ''
ENV DB_PASSWORD ''
ENV DB_PORT 27017

# optimize the performance by first installing packages and only after copying all the project files
COPY ./package*.json ./
RUN npm install
COPY ./ ./

EXPOSE ${PORT} ${DB_PORT}

CMD ["npm", "run", "test"]