import { defaultEnv, envTypes } from '../constants/configConstants.js';

const {
  NODE_ENV: ENV = defaultEnv,
  API_URL,
  PORT = 3000,

  DB_HOST,
  DB_NAME,
  DB_USER,
  DB_PASSWORD,

  TEST_DB_NAME,

  JWT_SECRET,
  JWT_EXPIRE = '1h',

  STATIC_FOLDER = 'public',
  TEMP_FOLDER = 'temp',

  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_FOLDER,

  SENDGRID_API_KEY,
  SENDGRID_EMAIL_FROM,
  SENDGRID_PASSWORD_RESET_TEMPLATE_ID,
  SENDGRID_EAMIL_VERIFICATION_TEMPLATE_ID,

  SENDGRID_SMTP_HOST,
  SENDGRID_SMTP_PORT,
  SENDGRID_SMTP_USERNAME,
  SENDGRID_SMTP_PASSWORD,

  MAILTRAP_SMTP_HOST,
  MAILTRAP_SMTP_PORT,
  MAILTRAP_SMTP_USERNAME,
  MAILTRAP_SMTP_PASSWORD,
  MAILTRAP_SMTP_EMAIL_FROM,

  CRYPTO_IV,
  CRYPTO_KEY,
} = process.env;

const DB = {
  DB_HOST,
  DB_NAME: ENV === envTypes.TEST ? TEST_DB_NAME : DB_NAME,
  DB_USER,
  DB_PASSWORD,
};

const SENDGRID_SMTP = {
  HOST: SENDGRID_SMTP_HOST,
  PORT: SENDGRID_SMTP_PORT,
  USERNAME: SENDGRID_SMTP_USERNAME,
  PASSWORD: SENDGRID_SMTP_PASSWORD,
  FROM: SENDGRID_EMAIL_FROM,
};

const MAILTRAP_SMTP = {
  HOST: MAILTRAP_SMTP_HOST,
  PORT: MAILTRAP_SMTP_PORT,
  USERNAME: MAILTRAP_SMTP_USERNAME,
  PASSWORD: MAILTRAP_SMTP_PASSWORD,
  FROM: MAILTRAP_SMTP_EMAIL_FROM,
};

const IS_DEV = ENV === envTypes.DEVELOPMENT;
const IS_PROD = ENV === envTypes.PRODUCTION;
const IS_TEST = ENV === envTypes.TEST;
const IS_STAGING = ENV === envTypes.STAGING;

export default {
  APP: {
    PORT,
    BASE_API_URL: IS_PROD ? `${API_URL}/api` : `${API_URL}:${PORT}/api`,
    API_URL: IS_PROD ? API_URL : `${API_URL}:${PORT}`,

    ENV,
    IS_DEV,
    IS_PROD,
    IS_TEST,
    IS_STAGING,
  },
  DB,
  TEST_DB: {
    DB_HOST,
    DB_NAME: TEST_DB_NAME,
    DB_USER,
    DB_PASSWORD,
  },
  JWT: {
    JWT_SECRET,
    JWT_EXPIRE,
  },
  FILE: {
    STATIC_FOLDER,
    TEMP_FOLDER,
  },
  CLOUDINARY: {
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_FOLDER,
  },
  SENDGRID: {
    API_KEY: SENDGRID_API_KEY,
    EMAIL_FROM: SENDGRID_EMAIL_FROM,
    PASSWORD_RESET_TEMPLATE_ID: SENDGRID_PASSWORD_RESET_TEMPLATE_ID,
    EAMIL_VERIFICATION_TEMPLATE_ID: SENDGRID_EAMIL_VERIFICATION_TEMPLATE_ID,
  },
  SMTP_EMAIL: IS_PROD ? SENDGRID_SMTP : MAILTRAP_SMTP,
  SENDGRID_SMTP,
  MAILTRAP_SMTP,
  CRYPTO: {
    IV: CRYPTO_IV,
    KEY: CRYPTO_KEY,
  },
};
